### ISSUE TITLE
pagination

### ISSUE THREAD

**Issue by joserodriguezballester** [Sgambe33/WarThunder-Vehicles-API#15]
I think an endpoint page is necessary to see the vehicles further than the limit=200 or to make the maximum limit larger.
If you enter 
http://wtvehiclesapi.sgambe.serv00.net/api/vehicles 
you get 50 Vehicles
http://wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=200
you get 200 Vehicles
http://wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=1000
you get 200 Vehicles
How do you see vehicle 201?
It would be something like this 
http://wtvehiclesapi.sgambe.serv00.net/api/vehicles?page=0?limit=50

**Comment by Sgambe33** [comment]
It is a feature that I already thought about implementing because I realize you can't see all the vehicles 😅

**Comment by m3xw3ll** [comment]
Hi @Sgambe33,
how exactly does pagination work now? 
Can you please show an example?

Thank you

**Comment by Sgambe33** [comment]
> Hi @Sgambe33, how exactly does pagination work now? Can you please show an example?
> 
> Thank you

Hi!
Simply use it a query parameter in this way:

`https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=200&page=0`

By default the value of page is 0 (when not specified) but can be incremented until you receive enough vehicles. Remember that the pagination  depends also from the limit parameter (max 200) . If you set limit=100 you will have many pages until the last one returns less than 100.

`https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=100&page=0`

`https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=100&page=0`

**Comment by m3xw3ll** [comment]
> > Hi @Sgambe33, how exactly does pagination work now? Can you please show an example?
> > Thank you
> 
> Hi! Simply use it a query parameter in this way:
> 
> `https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=200&page=0`
> 
> By default the value of page is 0 (when not specified) but can be incremented until you receive enough vehicles. Remember that the pagination depends also from the limit parameter (max 200) . If you set limit=100 you will have many pages until the last one returns less than 100.
> 
> `https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=100&page=0`
> 
> `https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=100&page=1`
> 
> `https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles?limit=100&page=2`

Sorry, I overlooked the page parameter. Thanks for the quick reply.
