### ISSUE TITLE
Seeking Assistance for Improved API Access for Developers in China

### ISSUE THREAD

**Issue by phquathi** [Sgambe33/WarThunder-Vehicles-API#21]
Dear Development Team,

Hello! I am a developer from China and I have encountered some issues accessing your API from my local environment. It seems that the requests do not return data, which might be due to geographical or network restrictions. I am eager to utilize your API effectively as it is crucial for my projects.

I understand that this might involve complex technical challenges, and I would like to collaborate with your team to explore possible solutions or adjustments to facilitate seamless access for Chinese developers. Could we consider adding specific features or do you have other suggestions to optimize the API access experience?

I appreciate your consideration of this request and look forward to your response. I am confident that together we can find a mutually satisfactory solution. Thank you for your time and assistance!

Best regards,
pHq

**Comment by phquathi** [comment]
Now my problem is over🤣🤣🤣. Initially, I was under the impression that I was unable to access data from your API due to potential regional restrictions. However, it turned out that the issue was simply that I could not open your API documentation, not that the data access itself was restricted. Fortunately, I’ve now managed to access the documentation and am pleased to report that I can successfully retrieve data without the need for a VPN or any special measures.

I would like to thank you for creating such a robust API, which is integral to my projects. Your efforts have greatly facilitated my work, and I am very grateful for the access and functionality provided.

Thank you once again for your support and for providing such valuable resources.

**Comment by Sgambe33** [comment]
@phquathi Happy that you managed to use this API and thanks for your support!
