### ISSUE TITLE
add "gunboat" in api description

### ISSUE THREAD

**Issue by i-peresvetov** [Sgambe33/WarThunder-Vehicles-API#22]
it's written in your api documentation:
Available values : lighttank, mediumtank, heavytank, tankdestroyer, spaa, fighter, stormovik, bomber, divebomber, torpedoboat, submarinechaser, minelayer, transport, navalferrybarge, destroyer, torpedogunboat, ship

but actually you have another one - "gunboat"
![image](https://github.com/Sgambe33/WarThunder-Vehicles-API/assets/56585233/f3ee2d2c-5d73-4dfd-95a3-55165a3a8afd)

**Comment by Sgambe33** [comment]
Thank you for pointing it out!
