### ISSUE TITLE
Adding Latest Tank from Major Update

### ISSUE THREAD

**Issue by Failcrafter1998** [Sgambe33/WarThunder-Vehicles-API#27]
When will the new Vehicles from the Seek and Destroy Major Update be added?

**Comment by Sgambe33** [comment]
They can be added right away. However I'm still wondering whether add new vehicles as soon as the update drops or wait a few patches to get their data fixed. I'm going to update the vehicles every major update so there are two options:
- Update as soons as major update hits.
- Keep data one update behind.

**Comment by Failcrafter1998** [comment]
I get you, i just wondered you fast you are going to add the news one. Im using your api from my Warthunder Clan. I coded a squadron battle tool where users can select wich vehicles they have and a bot prints me them in discord for the br that is atm active in squadron battles. For me it would be create to have them right away but i get that its alot of work for you

**Comment by Sgambe33** [comment]
> I get you, i just wondered how fast you are going to add the new ones. Im using your api from my Warthunder Clan. I coded a squadron battle tool where users can select wich vehicles they have and a bot prints me them in discord for the br that is atm active in squadron battles. For me it would be create to have them right away but i get that its alot of work for you

It's not how fast I am, it's what is better for users. Anyway, I'm adding the new update rn
