### ISSUE TITLE
Retrieving all data including vehicle specifics

### ISSUE THREAD

**Issue by JoshuaVdMerwe** [Sgambe33/WarThunder-Vehicles-API#28]
I intend to get all the data including all vehicle's specific info for a project.

I would use the API, it would just be a ton of requests to get the details for all the vehicles. I only need to retrieve the data once, by the way.

Would it be possible to send the db file so I can run it locally and get the data I need to avoid costing you an arm and a leg?

If not, I'll make sure to donate some $$ when I make those calls.

**Comment by Sgambe33** [comment]
Hi, you could just fetch all vehicles and save the data locally. If it's one time thing you can do it, no problem.
