### ISSUE TITLE
Some BR data is inaccurate

### ISSUE THREAD

**Issue by justinkohlenberg** [Sgambe33/WarThunder-Vehicles-API#29]
I started experimenting with the API, which is really nice btw.
However, I noticed that in some cases there is a discrepancy between the ingame BR for air realistic (maybe for the other modes as well) and the one returned by the API.

For example, ingame the A-10A Early is at an air realistic BR of 10.3, but looking at the API for this vehicle it returns 10
"realistic_br": 10,
"realistic_ground_br": 10.3,
"simulator_br": 10.3,
"simulator_ground_br": 10.3, 

https://www.wtvehiclesapi.sgambe.serv00.net/api/vehicles/a_10a_early

Another example is the (American) F-8E, F4C phantom II, (American) F-5E
Actually looking at it more in depth there is a lot of BR's that aren't right (in all nations).

I am not sure how you collect your data (I hope it is not manual for your sake 😅 ), but there may be something wrong with it

**Comment by Sgambe33** [comment]
Hi, this is because data is not updated to the latest game version but only to the last major update (seek and destroy). I know that there have been some usual BR changes but I did add them yet. I'll try and figure out a better way to keep the repo updated
