### ISSUE TITLE
Ive seen you are reworking the whole thing. I was kind of just browsing the issues on main gszabi Datamine Repo and saw your comment on you having an api

### ISSUE THREAD

**Issue by HealingArcYT** [Sgambe33/WarThunder-Vehicles-API#8]
I also kind of wanted to start an own project, but in python that visualizes all that data. So how far are you on your rework currently?

**Comment by HealingArcYT** [comment]
I will let you know when im somewhere

**Comment by HealingArcYT** [comment]
i have wondered, do you add each vehicle or do you have the actual parameters from the blkx files that you read to get all the information? i didnt find the country of planes in the blkx yet

**Comment by HealingArcYT** [comment]
ah i found something
`char.vromfs.bin_u\config\unittags.blkx` list of all vehicles, types and countries
`aces.vromfs.bin_u\gamedata\units\tankmodels` tank models
`aces.vromfs.bin_u\gamedata\units\ships` ship models
`aces.vromfs.bin_u\gamedata\flightmodels` flight models

**Comment by Sgambe33** [comment]
> i have wondered, do you add each vehicle or do you have the actual parameters from the blkx files that you read to get all the information? i didnt find the country of planes in the blkx yet

Basically yes, all the data is inside blkx file. For some specs you have to merge data from the vehicle blkx and a global config blkx called wpcost
